namespace: glued
name: laptop
version: 1.0.0
readme: README.md
authors:
- Pavel Stratil <pavel@senbonzakura.net>
license:
- BSD-3-Clause License
tags: []
dependencies: {}
repository: https://github.com/vaizard/ansible-collection-glued-laptop
documentation: https://github.com/vaizard/ansible-collection-glued-laptop
homepage: https://github.com/vaizard/ansible-collection-glued-laptop
issues: https://github.com/vaizard/ansible-collection-glued-laptop/issues
